---
- name: Ensure netplan is installed
  apt:
    name: netplan.io
    state: present

- name: Find current active network interface
  shell: ip -o link show | awk '{print $2,$9}' | grep 'UP' | head -n 1
  register: active_interface
  changed_when: false

- name: Extract interface name
  set_fact:
    interface_name: "{{ active_interface.stdout.split(':')[0] }}"

- name: Check if interface is eth0
  set_fact:
    is_eth0: "{{ 'eth0' in interface_name }}"

- name: Replace eth0 with net0 in /etc/netplan/50-cloud-init.yaml
  replace:
    path: /etc/netplan/50-cloud-init.yaml
    regexp: 'eth0'
    replace: 'net0'
  when: is_eth0

- name: Apply Netplan configuration
  command: netplan apply
  when: is_eth0

- name: Display information about the renamed interface
  shell: ip addr show net0
  register: interface_info
  changed_when: false
  when: is_eth0

- name: Display network interface info
  debug:
    msg: "{{ interface_info.stdout }}"
  when: is_eth0

- name: Display message if interface is not eth0
  debug:
    msg: "The network interface is not named eth0."
  when: not is_eth0